- assert:
    that:
     - "traefik_acme_email is defined"
     - "traefik_web_password is defined"

- name: Generate
  template: src="docker-compose.yml.j2" dest="{{ traefik_docker_compose_file }}"

- name: Create a network web
  docker_network:
    name: web

- docker_service:
    project_name: "{{ traefik_docker.project_name }}"
    definition: "{{ traefik_docker.definition }}"
